config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base   



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
   render text: "Hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
   
  end

  def contact
   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def full_title(page_title = '')
  base_title = 'Twitch'
  if page_title.empty?
   base_title
  else
   page_title + ' | ' + base_title
  end
 end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class= "footer">
 <small>
  Twitch by <a href="http://www.shalininair.com">Shalini Nair</a>
 </small>
 <nav>
  <ul>
   <li><%= link_to 'About', about_path %></li>
   <li><%= link_to 'Contact', contact_path %></li>
   <li><%= link_to 'News', 'http://www.rubyonrails.org' %></li>
  </ul>
 </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<div class="navbar navbar-fixed-top navbar-inverse">
 <div class= "container">
  <%= link_to 'Twitch', root_path, id: 'logo' %>
  <nav>
   <ul class= "nav navbar-nav navbar-right" >
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Help', help_path %></li>
    <li><%= link_to 'Log in', '#' %></li>
   </ul>
  </nav>
 </div>
 <nav>
 </nav>
</div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/header' %> 
 <div class= "container">
 <%= yield %>
 <%= render 'layouts/footer' %>
 </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>Twitch is a twitter-like app, developed on RoR 4.2.2</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
 Contact <a href="www.railstutorial.org/#contact">Ruby on Rails Tutorial</a> 
 for problems with this app.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
 <p>
  This is the helpsection for Twitch. For help on the 
  <a href="www.railstutorial.org">Ruby on Rails Tutorial</a>, refer
  <a href="www.railstutorial.org/help"><em></em>this help guide</a>. 
 </p>

app/views/static_pages/home.html.erb
<div class= "center jumbotron">
 <h1>Welcome to Twitch</h1>

 <h2>This is the home page for a Twitter-like app, based on 
  <a href="www.railstutorial.org">Ruby on Rails Tutorial</a>.
 </h2>

 <%= link_to 'Sign up now', signup_path, class: 'btn btn-lg btn-primary' %>
</div>

<%= link_to image_tag('rails.png', alt: 'Rails logo'), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<%= provide(:title, "Sign Up") %>
<h1>Sign Up</h1>
<p>This is the sign up page for new users.</p>